SGSISoft/SGSISoft/urls.py
__author__ = "Andres Betin, Jhonny Madera y Raul Martelo"
__copyright__ = "Copyright 2016, Universidad de Cartagena"
__credits__ = ["Andres Betin", "Jhonny Madera", "Raul Martelo",
                    "Grupo de Investigacion GIMATICA",
                    "Universidad de Cartagena"]
__license__ = "GPL"
__version__ = "1.0.0"
__status__ = "Production"

from django.conf.urls import patterns, include, url
from django.contrib import admin

#from model_report import report
import notifications
from django.conf import settings

admin.autodiscover()
#report.autodiscover()

urlpatterns = patterns('',

                       url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
                       url(r'^admin/', include(admin.site.urls)),
                       url('^inbox/notifications/', include(notifications.urls)),
                       url(r'', include('user_sessions.urls', 'user_sessions')),
                       url(r'^pass/', include('password_reset.urls')), #TODO Corregir paginas
                       url(r'^', include('home.urls')),
                       url(r'^autoevaluacion/', include('autoevaluacion.urls')),
                       url(r'^activos/', include('gestion_activos.urls')),
                       url(r'^documental/', include('gestion_documental.urls')),
                       url(r'^riesgos/', include('gestion_riesgos.urls')),
                       url(r'^roles/', include('gestion_roles.urls')),
                       url(r'^reports/', include('reports.urls')),
                       url(r'^upload/', include('fileupload.urls')),
                       #url(r'^reportes/', include('model_report.urls')),


)
urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

SGSISoft/gestion_activos/urls.py
__author__ = "Andres Betin, Jhonny Madera y Raul Martelo"
__copyright__ = "Copyright 2016, Universidad de Cartagena"
__credits__ = ["Andres Betin", "Jhonny Madera", "Raul Martelo",
                    "Grupo de Investigacion GIMATICA",
                    "Universidad de Cartagena"]
__license__ = "GPL"
__version__ = "1.0.0"
__status__ = "Production"

from django.conf.urls import patterns, url
from gestion_activos.views import *

urlpatterns = patterns('',
    url(r'^active/([\d]+)$', activeRender, name='vActivo'),#Detalle: pagina para informacion de activo
    url(r'^active/new$', activeNewRender, name='nActivo'),#Mostrar: pagina para crear activo
    url(r'^active$', activeAllRender, name='lActivo'),#Mostrar: pagina para listar activos
    url(r'^active/edit/([\d]+)$', activeEditRender, name='eActivo'),#Mostrar: pagina para EDITAR activos
    url(r'^active/all$', activeRead, name='activeRead'),#Listar: activos
    url(r'^active/delete$', activeDelete, name='activeDelete'),#Eliminar activos
    url(r'^active/search$', activeSearch, name='activeSearch'),#Listar: activos

    url(r'^resource/([\d]+)$', resourceRender, name='vRecurso'),#Detalle: pagina para informacion de activo
    url(r'^resource/new$', resourceNewRender, name='nRecurso'),#Mostrar: pagina para crear activo
    url(r'^resource$', resourceAllRender, name='lRecurso'),#Mostrar: pagina para listar activos
    url(r'^resource/edit/([\d]+)$', resourceEditRender, name='eRecurso'),#Mostrar: pagina para EDITAR activos
    url(r'^resource/all$', resourceRead, name='resourceRead'),#Listar: activos
    url(r'^resource/delete$', resourceDelete, name='resourceDelete'),#Eliminar activos
)

SGSISoft/home/urls.py
# -*- encoding: utf-8 -*-
__author__ = "Andres Betin, Jhonny Madera y Raul Martelo"
__copyright__ = "Copyright 2016, Universidad de Cartagena"
__credits__ = ["Andres Betin", "Jhonny Madera", "Raul Martelo",
                    "Grupo de Investigacion GIMATICA",
                    "Universidad de Cartagena"]
__license__ = "GPL"
__version__ = "1.0.0"
__status__ = "Production"

from django.conf.urls import patterns, url
from home.views import *

urlpatterns = patterns('',
        url(r'^$', home, name='inicio'),
        url(r'^login$', login, name='login'),
        url(r'^logout$', logout_view, name='logout'),
        #url(r'^notification$', notificationRender, name='notificaciones'), TODO: eliminar o reimplementar
        #url(r'^notification/([\d]+)$', notificationDetailRender, name='eNotificacion'), TODO: eliminar o reimplementar
        url(r'^notifications$', notificationsRead, name='notifications_ajax_read'),
)

SGSISoft/gestion_activos/models.py
# -*- encoding: utf-8 -*-
__author__ = "Andres Betin, Jhonny Madera y Raul Martelo"
__copyright__ = "Copyright 2016, Universidad de Cartagena"
__credits__ = ["Andres Betin", "Jhonny Madera", "Raul Martelo",
                    "Grupo de Investigacion GIMATICA",
                    "Universidad de Cartagena"]
__license__ = "GPL"
__version__ = "1.0.0"
__status__ = "Production"

from django.db import models
from gestion_roles.models import Persona

class TipoRecurso(models.Model):
    nombre = models.CharField(max_length=250)
    padre = models.ForeignKey('self',null=True, blank=True)
    descripcion = models.TextField()

# region Auditoria
    isDisable= models.BooleanField(default=False)
    createDate= models.DateTimeField(auto_now_add=True)
    createUser= models.TextField(null=True, blank=True)
    updateDate= models.DateTimeField(auto_now=True)
    updateUser= models.TextField(null=True, blank=True)

    def setDisable(self, disable):
        self.isDisable= disable

    def setUpdateUser(self, user):
        self.updateUser= user

    def setCreateUser(self, user):
        self.createUser= user
        self.updateUser= user
# endregion

    def __unicode__(self):
        return self.nombre

class TipoActivo(models.Model):
    nombre = models.CharField(max_length=250)
    padre = models.ForeignKey('self',null=True, blank=True)
    descripcion = models.TextField()

# region Auditoria
    isDisable= models.BooleanField(default=False)
    createDate= models.DateTimeField(auto_now_add=True)
    createUser= models.TextField(null=True, blank=True)
    updateDate= models.DateTimeField(auto_now=True)
    updateUser= models.TextField(null=True, blank=True)

    def setDisable(self, disable):
        self.isDisable= disable

    def setUpdateUser(self, user):
        self.updateUser= user

    def setCreateUser(self, user):
        self.createUser= user
        self.updateUser= user
# endregion

    def __unicode__(self):
        return self.nombre

# endregion

#region NoBorrables
class Activo(models.Model):
    codigo = models.CharField(max_length=10, unique=True)
    nombre = models.CharField(max_length=20)
    descripcion = models.TextField()
    dependencias = models.ManyToManyField("self", null=True, blank=True)
    responsables = models.ManyToManyField(Persona, null=True, blank=True)
    atributos = models.TextField()
    relevancia = models.CharField(max_length=15)
    cantidad = models.IntegerField(null = False)
    tipo = models.ForeignKey(TipoActivo,null=True, blank=True)


# region Auditoria
    isDisable= models.BooleanField(default=False)
    createDate= models.DateTimeField(auto_now_add=True)
    createUser= models.TextField(null=True, blank=True)
    updateDate= models.DateTimeField(auto_now=True)
    updateUser= models.TextField(null=True, blank=True)

    def setDisable(self, disable):
        self.isDisable= disable

    def setUpdateUser(self, user):
        self.updateUser= user

    def setCreateUser(self, user):
        self.createUser= user
        self.updateUser= user
# endregion

    def __unicode__(self):
        return self.nombre

class Recurso(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()
    activos = models.ManyToManyField(Activo,null=False,blank=False)
    tipo = models.ForeignKey(TipoRecurso)
    usuarios = models.ManyToManyField(Persona,null=False,blank=False)

# region Auditoria
    isDisable= models.BooleanField(default=False)
    createDate= models.DateTimeField(auto_now_add=True)
    createUser= models.TextField(null=True, blank=True)
    updateDate= models.DateTimeField(auto_now=True)
    updateUser= models.TextField(null=True, blank=True)

    def setDisable(self, disable):
        self.isDisable= disable

    def setUpdateUser(self, user):
        self.updateUser= user

    def setCreateUser(self, user):
        self.createUser= user
        self.updateUser= user
# endregion

    def __unicode__(self):
        return self.nombre









    

SGSISoft/gestion_activos/forms/ActivoForm.py
# -*- encoding: utf-8 -*-
__author__ = "Andres Betin, Jhonny Madera y Raul Martelo"
__copyright__ = "Copyright 2016, Universidad de Cartagena"
__credits__ = ["Andres Betin", "Jhonny Madera", "Raul Martelo",
                    "Grupo de Investigacion GIMATICA",
                    "Universidad de Cartagena"]
__license__ = "GPL"
__version__ = "1.0.0"
__status__ = "Production"

from django import forms
from django.forms.models import ModelForm
from gestion_activos.models import *
from gestion_activos.servicios import ActivoServicios
from util.Util import Util

class ActivoForm(ModelForm):
    def __init__(self, *args, **kwargs):
        self.edit = kwargs.pop('edit', None)
        super(ActivoForm, self).__init__(*args, **kwargs)

        self.activoServicios = ActivoServicios()

    class Meta:
        model = Activo
        exclude = ["relevancia","atributos"]
        selectMultiple = {'class': 'chzn-select', 'multiple': '', 'tabindex': '15', 'style': 'width:300px'}
        select = {'data-placeholder': "Seleccionar", 'class': "chzn-select", 'tabindex': "2"}

        widgets = {
            'responsables': forms.SelectMultiple(attrs=selectMultiple),
            'dependencias': forms.SelectMultiple(attrs=selectMultiple),
            'tipo': forms.Select(attrs=select),

        }

    def save(self, commit=True):
        if not self.edit:
            activo = super(ActivoForm, self).save(commit=False)

            self.activoServicios.insert(activo)
            self.save_m2m()
        else:
            activo = super(ActivoForm, self).save(commit=False)

            self.save_m2m()
            self.activoServicios.update(activo)

SGSISoft/gestion_activos/forms/RecursoForm.py
# -*- encoding: utf-8 -*-
__author__ = "Andres Betin, Jhonny Madera y Raul Martelo"
__copyright__ = "Copyright 2016, Universidad de Cartagena"
__credits__ = ["Andres Betin", "Jhonny Madera", "Raul Martelo",
                    "Grupo de Investigacion GIMATICA",
                    "Universidad de Cartagena"]
__license__ = "GPL"
__version__ = "1.0.0"
__status__ = "Production"

from gestion_activos.models import Recurso
from django import forms
from django.forms.models import ModelForm
from gestion_activos.servicios.RecursoServicios import RecursoServicios

class RecursoForm(ModelForm):
    def __init__(self, *args, **kwargs):
        self.edit = kwargs.pop('edit', None)
        super(RecursoForm, self).__init__(*args, **kwargs)

        self.recursoServicios = RecursoServicios()

    class Meta:
        model = Recurso

        selectMultiple = {'class': 'chzn-select', 'multiple': '', 'tabindex': '15', 'style': 'width:300px'}
        select = {'data-placeholder': "Seleccionar", 'class': "chzn-select", 'tabindex': "2"}

        widgets = {
            'activos': forms.SelectMultiple(attrs=selectMultiple),
            'usuarios': forms.SelectMultiple(attrs=selectMultiple),
            'tipo':forms.Select(attrs=select)
        }

    def save(self, commit=True):
        if not self.edit:
            recurso = super(RecursoForm, self).save(commit=False)

            self.recursoServicios.insert(recurso)
            self.save_m2m()
        else:
            recurso = super(RecursoForm, self).save(commit=False)

            self.save_m2m()
            self.recursoServicios.update(recurso)

SGSISoft/gestion_activos/views.py
__author__ = "Andres Betin, Jhonny Madera y Raul Martelo"
__copyright__ = "Copyright 2016, Universidad de Cartagena"
__credits__ = ["Andres Betin", "Jhonny Madera", "Raul Martelo",
                    "Grupo de Investigacion GIMATICA",
                    "Universidad de Cartagena"]
__license__ = "GPL"
__version__ = "1.0.0"
__status__ = "Production"

# Create your views here.
import json
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, HttpResponse
from gestion_activos.forms import ActivoForm
from gestion_activos.servicios import ActivoServicios
from util.Util import Util
from gestion_activos.forms import RecursoForm
from gestion_activos.servicios.RecursoServicios import RecursoServicios
from gestion_activos.models import Activo

activoServicios = ActivoServicios()
recursoServicios = RecursoServicios()

# region Active Render
def activeRender(request,id):
    if request.method == 'GET':
        activo = activoServicios.get(id)
        recursos = recursoServicios.getRecursosByActivo(activo)
    return Util.pagina(request, "gestion_activos/activo_detalle.html", {'activo':activo, 'recursos':recursos})

def activeNewRender(request):
    if request.method == 'POST':
        formulario = ActivoForm(request.POST)
        if formulario.is_valid():
            formulario.save()
            return HttpResponseRedirect(reverse('lActivo'))
    else:
        formulario = ActivoForm()

    return Util.pagina(request, "gestion_activos/activo_form.html", {'formulario':formulario})


def activeEditRender(request, id):
    activo = activoServicios.get(id)
    if request.method == 'POST':
        formulario = ActivoForm(request.POST, edit=True,instance=activo)
        if formulario.is_valid():
            formulario.save()
            return HttpResponseRedirect(reverse('lActivo'))
    else:
        formulario = ActivoForm(instance=activo)

    return Util.pagina(request, 'gestion_activos/activo_form.html', {'formulario': formulario})


def activeAllRender(request):

    return Util.pagina(request, 'gestion_activos/activo_listar.html',{})


# endregion

# region Active Object
def activeRead(request):
    if request.is_ajax():
        activos = activoServicios.getAll()
        respuesta = [activoServicios.getDTO(activo) for activo in activos]
        serializado = json.dumps(respuesta)
        return HttpResponse(serializado, content_type="application/json")

    return HttpResponse("Pagina no encontrada", content_type="application/json", status=404)

def activeSearch(request):
    if request.is_ajax():
        query = request.GET['query']
        activos = activoServicios.whereLike(query)
        respuesta = [activoServicios.getDTO(activo) for activo in activos]
        serializado = json.dumps(respuesta)
        return HttpResponse(serializado, content_type="application/json")

    return HttpResponse("Pagina no encontrada", content_type="application/json", status=404)


def activeDelete(request):
    if request.is_ajax():
        idActivo = request.GET['idActivo']
        activo = activoServicios.get(idActivo)
        activoServicios.delete(activo)
        respuesta = []
        serializado = json.dumps(respuesta)
        return HttpResponse(serializado, content_type="application/json")

    return HttpResponse("Pagina no encontrada", content_type="application/json", status=404)

# endregion

# region Resource Render
def resourceRender(request,id):
    if request.method == 'GET':
        recurso = recursoServicios.get(id)
    return Util.pagina(request, "gestion_activos/recurso_detalle.html", {'recurso':recurso})

def resourceNewRender(request):
    if request.method == 'POST':
        formulario = RecursoForm(request.POST)
        print formulario.errors
        if formulario.is_valid():
            formulario.save()
            return HttpResponseRedirect(reverse('lRecurso'))
    else:
        formulario = RecursoForm()

    return Util.pagina(request, "gestion_activos/recurso_form.html", {'formulario':formulario})


def resourceEditRender(request, id):
    recurso = recursoServicios.get(id)
    if request.method == 'POST':
        formulario = RecursoForm(request.POST, edit=True,instance=recurso)
        if formulario.is_valid():
            formulario.save()
            return HttpResponseRedirect(reverse('lRecurso'))
    else:
        formulario = RecursoForm(instance=recurso)

    return Util.pagina(request, 'gestion_activos/recurso_form.html', {'formulario': formulario})


def resourceAllRender(request):

    return Util.pagina(request, 'gestion_activos/recurso_listar.html',{})


# endregion


# region Resource Object
def resourceRead(request):
    if request.is_ajax():
        recursos = recursoServicios.getAll()
        respuesta = [recursoServicios.getDTO(recurso) for recurso in recursos]


        #serializado = json.dumps(respuesta, ensure_ascii=False)
        serializado = json.dumps(respuesta)

        return HttpResponse(serializado, content_type="application/json")

    return HttpResponse("Pagina no encontrada", content_type="application/json", status=404)

def resourceDelete(request):
    if request.is_ajax():
        idRecurso = request.GET['idRecurso']
        recurso = recursoServicios.get(idRecurso)
        recursoServicios.delete(recurso)
        respuesta = []
        serializado = json.dumps(respuesta)
        return HttpResponse(serializado, content_type="application/json")

    return HttpResponse("Pagina no encontrada", content_type="application/json", status=404)

# endregion

SGSISoft/templates/gestion_activos/activo_form.html
<!--
Autor: Andres Betin, Jhonny Madera y Raul Martelo
Copyright: Copyright 2016, Universidad de Cartagena
Credits: Andres Betin, Jhonny Madera, Raul Martelo,
         Grupo de investigacion GIMATICA
         Universidad de Cartagena
License: GPL
Version: 1.0.0
Status: Production
-->

{% extends "dashboard.html" %}

{% block zonaTrabajo %}

    <div class="container-fluid">
        <ul class="breadcrumb">
            <li><a href="#">Gestión Activos</a><span class="divider">&raquo;</span></li>

            <li class="active">crear Activo</li>
        </ul>
        <div class="row-fluid">
            <div class="span12">
                <div class="nonboxy-widget">
                    <div class="widget-head">
                        <h5> Crear Activo</h5>
                    </div>
                    <div class="widget-content">
                        <div class="widget-box">
                            <div class="alert alert-success fade in">
                                <button data-dismiss="alert" class="close" type="button">×</button>
                                <strong>Actividad creada!</strong> Su actividad se ha creada de manera éxitosa se le
                                notificara a los usuarios encargados.
                            </div>

                            <form class="form-horizontal well" method="POST">
                                {% csrf_token %}
                                <fieldset>
                                    <div class="control-group">
                                        <label class="control-label" for="id_codigo">Código</label>

                                        <div class="controls">
                                            {{ formulario.codigo }}
                                        </div>
                                    </div>
                                    <div class="control-group">
                                        <label class="control-label" for="id_nombre">Nombre</label>

                                        <div class="controls">
                                            {{ formulario.nombre }}
                                        </div>
                                    </div>
                                    <div class="control-group">
                                        <label class="control-label" for="id_descripcion">Descripción</label>

                                        <div class="controls">
                                            {{ formulario.descripcion }}
                                        </div>
                                    </div>
                                    <div class="control-group">
                                        <label class="control-label" for="typehead">Cantidad</label>

                                        <div class="controls">
                                            {{ formulario.cantidad }}
                                        </div>
                                    </div>
                                    <div class="control-group">
                                        <label class="control-label" for="typehead">Tipo</label>

                                        <div class="controls">
                                            {{ formulario.tipo }}
                                        </div>
                                    </div>
                                    <div class="control-group">
                                        <label class="control-label" for="typehead">Dependencias</label>

                                        <div class="controls">
                                            {{ formulario.dependencias }}
                                        </div>
                                    </div>

                                    <div class="control-group">
                                        <label class="control-label" for="typehead">Responsable</label>

                                        <div class="controls">
                                            {{ formulario.responsables }}
                                        </div>
                                    </div>
                                </fieldset>
                                <fieldset>
                                    <div class="form-actions">
                                        <button type="submit" class="btn btn-info">Guardar</button>
                                        <button class="btn btn-warning">Cancelar</button>
                                    </div>
                                </fieldset>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
    </div>
{% endblock %}

SGSISoft/templates/gestion_activos/activo_listar.html
<!--
Autor: Andres Betin, Jhonny Madera y Raul Martelo
Copyright: Copyright 2016, Universidad de Cartagena
Credits: Andres Betin, Jhonny Madera, Raul Martelo,
         Grupo de investigacion GIMATICA
         Universidad de Cartagena
License: GPL
Version: 1.0.0
Status: Production
-->

{% extends "dashboard.html" %}
{% block zonaTrabajo %}
    <script src="{{ STATIC_URL }}js/gestion_activos/activos.js"></script>
    <script src="{{ STATIC_URL }}js/constates/constantes.js"></script>
    <script>
        $(document).ready(function () {
            activos.inicializar();
        });
    </script>
    <div class="container-fluid">
        <ul class="breadcrumb">
            <li><a href="{% url inicio %}">Inicio</a><span class="divider">&raquo;</span></li>
            <li><a href="#">Gestion de Activos</a><span class="divider">&raquo;</span></li>
            <li class="active">Activos</li>
        </ul>
        <div class="row-fluid">
            <div class="span12">
                <div class="widget-block">
                    <div class="widget-head">
                        <h5>Gestion De Activos</h5>

                        <div class="widget-control pull-right">
                        </div>
                    </div>
                    <div class="widget-content">
                        <div class="widget-box">
                            <table class="table" id="table_active">
                                <thead>
                                <tr>
                                   <th>
                                        Código
                                    </th>
                                    <th>
                                        Nombre
                                    </th>
                                    <th>
                                        Descripción
                                    </th>
                                    <th>
                                        Cantidad
                                    </th>
                                    <th>
                                        Tipo
                                    </th>
                                    <th>
                                        Dependencias
                                    </th>
                                    <th>
                                        Responsables
                                    </th>
                                    <th>

                                    </th>
                                </tr>
                                </thead>
                            </table>
                            <div class="modal hide fade" id="modal_confirmacion">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal">×
                                    </button>
                                    <h3>Eliminación</h3>
                                </div>

                                <div class="modal-body">
                                    ¿Está seguro que desea eliminar el activo: <b><span id="nombre_activo"></span></b>?
                                </div>
                                <div class="modal-footer">
                                    <button class="btn btn-danger" data-dismiss="modal" id="bDeleteActive">
                                        Eliminar
                                    </button>
                                    <button class="btn btn-warning" data-dismiss="modal">Cancelar</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

SGSISoft/templates/gestion_activos/recurso_form.html
<!--
Autor: Andres Betin, Jhonny Madera y Raul Martelo
Copyright: Copyright 2016, Universidad de Cartagena
Credits: Andres Betin, Jhonny Madera, Raul Martelo,
         Grupo de investigacion GIMATICA
         Universidad de Cartagena
License: GPL
Version: 1.0.0
Status: Production
-->

{% extends "dashboard.html" %}

{% block zonaTrabajo %}

    <div class="container-fluid">
        <ul class="breadcrumb">
            <li><a href="#">Gestión Activos</a><span class="divider">&raquo;</span></li>

            <li class="active">crear Activo</li>
        </ul>
        <div class="row-fluid">
            <div class="span12">
                <div class="nonboxy-widget">
                    <div class="widget-head">
                        <h5> Crear Recurso</h5>
                    </div>
                    <div class="widget-content">
                        <div class="widget-box">
                            <div class="alert alert-success fade in">
                                <button data-dismiss="alert" class="close" type="button">×</button>
                                <strong>Actividad creada!</strong> Su actividad se ha creada de manera éxitosa se le
                                notificara a los usuarios encargados.
                            </div>

                            <form class="form-horizontal well" method="POST">
                                {% csrf_token %}
                                <fieldset>
                                    <div class="control-group">
                                        <label class="control-label" for="id_nombre">Nombre</label>

                                        <div class="controls">
                                            {{ formulario.nombre }}
                                        </div>
                                    </div>
                                    <div class="control-group">
                                        <label class="control-label" for="id_descripcion">Descripción</label>

                                        <div class="controls">
                                            {{ formulario.descripcion }}
                                        </div>
                                    </div>
                                    <div class="control-group">
                                        <label class="control-label" for="typehead">Tipo</label>

                                        <div class="controls">
                                            {{ formulario.tipo }}
                                        </div>
                                    </div>
                                    <div class="control-group">
                                        <label class="control-label" for="typehead">Activos que soporta</label>

                                        <div class="controls">
                                            {{ formulario.activos }}
                                        </div>
                                    </div>

                                    <div class="control-group">
                                        <label class="control-label" for="typehead">Usuarios</label>

                                        <div class="controls">
                                            {{ formulario.usuarios }}
                                        </div>
                                    </div>
                                </fieldset>
                                <fieldset>
                                    <div class="form-actions">
                                        <button type="submit" class="btn btn-info">Guardar</button>
                                        <button class="btn btn-warning">Cancelar</button>
                                    </div>
                                </fieldset>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
    </div>
{% endblock %}