SGSISoft/SGSISoft/urls.py
__author__ = "Andres Betin, Jhonny Madera y Raul Martelo"
__copyright__ = "Copyright 2016, Universidad de Cartagena"
__credits__ = ["Andres Betin", "Jhonny Madera", "Raul Martelo",
                    "Grupo de Investigacion GIMATICA",
                    "Universidad de Cartagena"]
__license__ = "GPL"
__version__ = "1.0.0"
__status__ = "Production"

from django.conf.urls import patterns, include, url
from django.contrib import admin

#from model_report import report
import notifications
from django.conf import settings

admin.autodiscover()
#report.autodiscover()

urlpatterns = patterns('',

                       url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
                       url(r'^admin/', include(admin.site.urls)),
                       url('^inbox/notifications/', include(notifications.urls)),
                       url(r'', include('user_sessions.urls', 'user_sessions')),
                       url(r'^pass/', include('password_reset.urls')), #TODO Corregir paginas
                       url(r'^', include('home.urls')),
                       url(r'^autoevaluacion/', include('autoevaluacion.urls')),
                       url(r'^activos/', include('gestion_activos.urls')),
                       url(r'^documental/', include('gestion_documental.urls')),
                       url(r'^riesgos/', include('gestion_riesgos.urls')),
                       url(r'^roles/', include('gestion_roles.urls')),
                       url(r'^reports/', include('reports.urls')),
                       url(r'^upload/', include('fileupload.urls')),
                       #url(r'^reportes/', include('model_report.urls')),


)
urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

SGSISoft/gestion_roles/urls.py
# -*- encoding: utf-8 -*-
__author__ = "Andres Betin, Jhonny Madera y Raul Martelo"
__copyright__ = "Copyright 2016, Universidad de Cartagena"
__credits__ = ["Andres Betin", "Jhonny Madera", "Raul Martelo",
                    "Grupo de Investigacion GIMATICA",
                    "Universidad de Cartagena"]
__license__ = "GPL"
__version__ = "1.0.0"
__status__ = "Production"

from gestion_roles.views import *
from django.conf.urls import patterns, url
#url(r'^$', index, name='roles.index'),
urlpatterns = patterns('',
    url(r'^user$', userAllRender, name='lUsuario'),#Mostrar: pagina administracion usuarios
    url(r'^user/all$', userRead, name='userRead'),#listar: usuarios
    url(r'^user/new$', userNewRender, name='nUsuario'),#Mostrar: formulario para CREAR usuario
    url(r'^user/new_ajax$', userNewPost, name='nUsuario_ajax'),#ajax: Ajax para CREAR usuario.
    url(r'^user/edit/([\d]+)$', userEditRender, name='eUsuario'),#Mostrar: formulario para EDITAR usuario
    url(r'^user/edit_ajax/([\d]+)$', userEditPost, name='eUsuario_ajax'),#ajax: ajax para EDITAR usuario
    url(r'^user/delete$', userDelete, name='userDelete'),#Eliminar: usuario
    url(r'^user/groups$', userGroupsRead, name='userGroupsRead'),#Listar: Grupos al que pertenece el usuario
    url(r'^user/([\d]+)$', userRender, name='vUsuario'),#Detalle: de informacion del usuario determinado
    url(r'^userprofile$', userProfileRender, name='userProfile'),#Detalle: de informacion del usuario determinado

    url(r'^group$', groupAllRender, name='lGrupo'),#Mostrar: pagina para listar grupo
    url(r'^group/all$', groupRead, name='groupRead'),#Listar: grupos
    url(r'^group/new$', groupNewRender, name='nGrupo'),#Mostrar pagina para CREAR grupo
    url(r'^group/new_ajax$', groupNewPost, name='nGrupo_ajax'),#ajax: Ajax para crear usuario.
    url(r'^group/edit/([\d]+)$', groupEditRender, name='eGrupo'),#Mostrar: pagina para EDITAR grupo
    url(r'^group/edit_ajax/([\d]+)$', groupEditPost, name='eGrupo_ajax'),#ajax: ajax para EDITAR grupo
    url(r'^group/delete$', groupDelete, name='groupDelete'),#Eliminar: grupo
    url(r'^group/users$', groupUsersRead, name='groupUsersRead'),#Listar: usuarios de un grupo
    url(r'^group/no-users$', groupNoUsersRead, name='groupNoUsersRead'),#Listar: usuarios de un grupo
    url(r'^group/users-add$', groupAddUser, name='groupUsersAdd'),#Agregar: Agregar usuarios a un grupo
    url(r'^group/users-remove$', groupRemoveUser, name='groupUsersRemove'),#Remover: remover usuarios de un grupo
    url(r'^group/([\d]+)$', groupRender, name='vGrupo'),#Detalle: informacion de grupo

    #url(r'^permission/([\w]+)/([\d]+)$', permissionRender, name='aPermiso'),#Mostrar pagina de administracion de permisos grupo o usuario determinado TODO: quitar
    url(r'^permission/all$', permissionRead, name='permissionRead'),#Listar permisos
    url(r'^permission/create$', permissionCreate, name='nPermiso'),#Crear permiso
    url(r'^permission/delete$', permissionDelete, name='dPermiso'),#Eliminar permiso
    url(r'^permission/update$', permissionUpdate, name='uPermiso'),#Actualizar permiso

    url(r'^permissionmaster/all$', permissionMasterRead, name='permissionReadMaster'),#Listar permisos
    url(r'^permissionmaster/setadmin$', permissionMasterSetAdmin, name='permissionSetAdminMaster'),#Modificar si el usuario es Administrador
    url(r'^permissionmaster/create$', permissionMasterCreate, name='nPermisoMaster'),#Crear permiso
    url(r'^permissionmaster/delete$', permissionMasterDelete, name='dPermisoMaster'),#Eliminar permiso

    url(r'^setpassword$', setPassword, name='user_setpassword'),
    url(r'^key/(?P<confirmation_key>\w+)/$', confirm_email, name='confirm_email'),
)

SGSISoft/home/urls.py
# -*- encoding: utf-8 -*-
__author__ = "Andres Betin, Jhonny Madera y Raul Martelo"
__copyright__ = "Copyright 2016, Universidad de Cartagena"
__credits__ = ["Andres Betin", "Jhonny Madera", "Raul Martelo",
                    "Grupo de Investigacion GIMATICA",
                    "Universidad de Cartagena"]
__license__ = "GPL"
__version__ = "1.0.0"
__status__ = "Production"

from django.conf.urls import patterns, url
from home.views import *

urlpatterns = patterns('',
        url(r'^$', home, name='inicio'),
        url(r'^login$', login, name='login'),
        url(r'^logout$', logout_view, name='logout'),
        #url(r'^notification$', notificationRender, name='notificaciones'), TODO: eliminar o reimplementar
        #url(r'^notification/([\d]+)$', notificationDetailRender, name='eNotificacion'), TODO: eliminar o reimplementar
        url(r'^notifications$', notificationsRead, name='notifications_ajax_read'),
)

SGSISoft/gestion_roles/models.py
# -*- encoding: utf-8 -*-
__author__ = "Andres Betin, Jhonny Madera y Raul Martelo"
__copyright__ = "Copyright 2016, Universidad de Cartagena"
__credits__ = ["Andres Betin", "Jhonny Madera", "Raul Martelo",
                    "Grupo de Investigacion GIMATICA",
                    "Universidad de Cartagena"]
__license__ = "GPL"
__version__ = "1.0.0"
__status__ = "Production"

from django.contrib.auth.models import User
from django.db import models
from mptt.models import MPTTModel, TreeForeignKey
from django.dispatch import receiver
from email_confirm_la.signals import post_email_confirm
from django.core.urlresolvers import reverse

#region Enumeraciones
from util.Util import EnumElemento


class Rol:
    USUARIO=EnumElemento("Usuario", 1, peso=1)
    LECTOR=EnumElemento("Lector", 2, peso=2)
    ESCRITOR=EnumElemento("Escritor", 3, peso=3)
    ADMINISTRADOR=EnumElemento("Administrador", 4, peso=4)

    @staticmethod
    def listaEnumerada():
        return [(value.getValor(), value.getNombre()) for key, value in Rol.__dict__.iteritems() if isinstance(value, EnumElemento)]

    @staticmethod
    def listaElementos():
        return [value for key, value in Rol.__dict__.iteritems() if isinstance(value, EnumElemento)]

    @staticmethod
    def get(id):
        valord= [value for key, value in Rol.__dict__.iteritems() if isinstance(value, EnumElemento) and value.getValor()==id][0]
        return valord
#endregion

#region Borrables
class Permiso(MPTTModel):
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()
    parent = TreeForeignKey("self", blank=True, null=True, related_name='children', db_index=True)
    funcion = models.CharField(max_length=150, blank=True, null=True)
    modulo = models.CharField(max_length=150)
    path = models.CharField(default=funcion, max_length=200, auto_created=True, unique=True)
    urlPath = models.CharField(max_length=150, blank=True, null=True)
    tipoPermiso = models.CharField(max_length=150)
    imagen = models.TextField()

# region Auditoria
    createDate= models.DateTimeField(auto_now_add=True)
    createUser= models.TextField(null=True, blank=True)
    updateDate= models.DateTimeField(auto_now=True)
    updateUser= models.TextField(null=True, blank=True)

    def setUpdateUser(self, user):
        self.updateUser= user

    def setCreateUser(self, user):
        self.createUser= user
        self.updateUser= user
#endregion

    def __unicode__(self):
        return self.nombre

    class MPTTMeta:
        order_insertion_by = ['nombre']

class Departamento(models.Model):
    nombre = models.CharField(max_length=50)

# region Auditoria
    isDisable= models.BooleanField(default=False)
    createDate= models.DateTimeField(auto_now_add=True)
    createUser= models.TextField(null=True, blank=True)
    updateDate= models.DateTimeField(auto_now=True)
    updateUser= models.TextField(null=True, blank=True)

    def setDisable(self, disable):
        self.isDisable= disable

    def setUpdateUser(self, user):
        self.updateUser= user

    def setCreateUser(self, user):
        self.createUser= user
        self.updateUser= user
# endregion

    def __unicode__(self):
        return self.nombre

class Cargo(models.Model):
    nombre = models.CharField(max_length=50)

# region Auditoria
    isDisable= models.BooleanField(default=False)
    createDate= models.DateTimeField(auto_now_add=True)
    createUser= models.TextField(null=True, blank=True)
    updateDate= models.DateTimeField(auto_now=True)
    updateUser= models.TextField(null=True, blank=True)

    def setDisable(self, disable):
        self.isDisable= disable

    def setUpdateUser(self, user):
        self.updateUser= user

    def setCreateUser(self, user):
        self.createUser= user
        self.updateUser= user
# endregion

    def __unicode__(self):
        return self.nombre
# endregion

# region NoBorrables
class Persona(models.Model):
    identificacion = models.CharField(max_length=20, unique=True)
    nombre = models.CharField(max_length=20)
    apellido = models.CharField(max_length=20)
    email = models.EmailField(unique=True)
    fechaNacimiento = models.DateField()
    usuario = models.ForeignKey(User)
    cargo = models.ForeignKey(Cargo)
    departamento = models.ForeignKey(Departamento)
    foto = models.TextField(blank=True)

# region Auditoria
    isDisable= models.BooleanField(default=False)
    createDate= models.DateTimeField(auto_now_add=True)
    createUser= models.TextField(null=True, blank=True)
    updateDate= models.DateTimeField(auto_now=True)
    updateUser= models.TextField(null=True, blank=True)

    def setDisable(self, disable):
        self.isDisable= disable

    def setUpdateUser(self, user):
        self.updateUser= user

    def setCreateUser(self, user):
        self.createUser= user
        self.updateUser= user
# endregion

    def __unicode__(self):
        return self.nombre + " " + self.apellido

class Grupo(models.Model):# Grupo no es NoBorrable. Los grupos se pueden eliminar. No mantienen relaciones.
    nombre = models.CharField(max_length=50, unique=True)
    personas = models.ManyToManyField(Persona, blank=True)

# region Auditoria
    createDate= models.DateTimeField(auto_now_add=True)
    createUser= models.TextField(null=True, blank=True)
    updateDate= models.DateTimeField(auto_now=True)
    updateUser= models.TextField(null=True, blank=True)

    def setUpdateUser(self, user):
        self.updateUser= user

    def setCreateUser(self, user):
        self.createUser= user
        self.updateUser= user
# endregion

    def __unicode__(self):
        return self.nombre
# endregion

# region Relaciones
class PersonaPermiso(models.Model):
    rol = models.IntegerField(choices=Rol.listaEnumerada())
    usuario = models.ForeignKey(Persona)
    permiso = models.ForeignKey(Permiso)

# region Auditoria
    createDate= models.DateTimeField(auto_now_add=True)
    createUser= models.TextField(null=True, blank=True)
    updateDate= models.DateTimeField(auto_now=True)
    updateUser= models.TextField(null=True, blank=True)

    def setUpdateUser(self, user):
        self.updateUser= user

    def setCreateUser(self, user):
        self.createUser= user
        self.updateUser= user
# endregion

    def __unicode__(self):
        return "{0:s} {1:s}".format(self.usuario.usuario.username, self.permiso.nombre)

class GrupoPermiso(models.Model):
    rol = models.IntegerField(choices=Rol.listaEnumerada())
    grupo = models.ForeignKey(Grupo)
    permiso = models.ForeignKey(Permiso)

# region Auditoria
    createDate= models.DateTimeField(auto_now_add=True)
    createUser= models.TextField(null=True, blank=True)
    updateDate= models.DateTimeField(auto_now=True)
    updateUser= models.TextField(null=True, blank=True)

    def setUpdateUser(self, user):
        self.updateUser= user

    def setCreateUser(self, user):
        self.createUser= user
        self.updateUser= user
# endregion

    def __unicode__(self):
        return "{0:s} {1:s}".format(self.grupo.nombre, self.permiso.nombre)
# endregion

#region utilitarias
class MenuItem:
    """Clase para representar un item del menu"""
    nombre = ""
    descripcion = ""
    funcion = ""
    modulo = ""
    path = ""
    tipoPermiso = ""
    imagen = ""
    urlPath = ""

    def __init__(self, permiso):
        self.nombre = permiso.nombre
        self.descripcion = permiso.descripcion
        self.funcion = permiso.funcion
        self.modulo = permiso.modulo
        self.path = permiso.path
        self.tipoPermiso = permiso.tipoPermiso
        self.imagen = permiso.imagen
        self.urlPath = reverse(permiso.urlPath) if permiso.urlPath is not None and permiso.urlPath != '' else ''

    def __eq__(self, other):
        if isinstance(other, MenuItem):
            return self.nombre == other.nombre
        return NotImplemented

class MenuGroup(MenuItem):
    """Clase para agrupar las aplicaciones"""
    name= ""
    menuItems = list()

    def __eq__(self, other):
        if isinstance(other, MenuGroup):
            return self.nombre == other.nombre
        return NotImplemented

#endregion

@receiver(post_email_confirm)
def post_email_confirm_callback(sender, confirmation, **kwargs):
    model_instace = confirmation.content_object
    email = confirmation.email

    model_instace.is_active = True
    model_instace.save()

SGSISoft/gestion_roles/forms/ContrasenaForm.py
# -*- encoding: utf-8 -*-
# -*- decoding: utf-8 -*-
__author__ = "Andres Betin, Jhonny Madera y Raul Martelo"
__copyright__ = "Copyright 2016, Universidad de Cartagena"
__credits__ = ["Andres Betin", "Jhonny Madera", "Raul Martelo",
                    "Grupo de Investigacion GIMATICA",
                    "Universidad de Cartagena"]
__license__ = "GPL"
__version__ = "1.0.0"
__status__ = "Production"

from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from util.Constantes import Constantes

from django import forms

class ContrasenaForm(forms.Form):

    contrasena_actual = forms.CharField(max_length=20, widget=forms.PasswordInput)
    contrasena = forms.CharField(max_length=20, widget=forms.PasswordInput, label='Ingrese nueva contraseña')
    contrasena2 = forms.CharField(max_length=20, widget=forms.PasswordInput, label='Repita la contraseña')

    def __init__(self, *args, **kwargs):
        self.usuario = kwargs.pop('usuario', None)
        super(ContrasenaForm, self).__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = self.cleaned_data

        contra_act = cleaned_data.get("contrasena_actual")
        contra = cleaned_data.get("contrasena")
        contra2 = cleaned_data.get("contrasena2")

        if not contra == contra2:
            raise forms.ValidationError(Constantes.ERROR_CONTRASENAS_NO_COINCIDEN)

        try:
            usu2 = User.objects.get(username=self.usuario.username)
            if not self.usuario.check_password(contra_act):
                raise forms.ValidationError(Constantes.ERROR_CONTRASENA_INCORRECTA)
        except ObjectDoesNotExist:
            raise forms.ValidationError(Constantes.ERROR_USUARIO_NO_EXISTE)

        return cleaned_data

    def save(self, request, commit=True):
        usuario = self.usuario
        contrasena_f = self.cleaned_data['contrasena']
        usuario.set_password(contrasena_f)
        usuario.save()
        #TODO: enviar correo con confirmacion de contraseña y notificar al usuario en growl

SGSISoft/gestion_roles/templates/grupo_detalle.html
<!--
Autor: Andres Betin, Jhonny Madera y Raul Martelo
Copyright: Copyright 2016, Universidad de Cartagena
Credits: Andres Betin, Jhonny Madera, Raul Martelo,
         Grupo de investigacion GIMATICA
         Universidad de Cartagena
License: GPL
Version: 1.0.0
Status: Production
-->

{% comment %}{% extends 'dashboard.html' %}

{% block zonaTrabajo %}
    <script src="{{ STATIC_URL }}js/gestion_roles/usuarios.js"></script>
    <script src="{{ STATIC_URL }}js/gestion_roles/permisos.js"></script>
    <script src="{{ STATIC_URL }}js/constates/constantes.js"></script>
    <script>
        $(document).ready(function () {
            usuarios.idResponsable = parseInt({{ grupo.id }})
            permisos.idResponsable = parseInt({{ grupo.id }})
            permisos.tipoResponsable = "group"
            usuarios.readUserGroup()
            permisos.read()
        });
    </script>{% endcomment %}
<div class="container-fluid">
    <div class="row-fluid">
        <div id="tabs">
            <ul>
                <li><a href="#tabs-1">Miembros</a></li>
                <li><a href="#tabs-2">Permisos</a></li>
            </ul>
            <div id="tabs-1">
                <div class="widget-block">
                    <div class="widget-head">
                        <h5>MIEMBROS</h5>
                    </div>
                    <div class="widget-content">
                        <div class="widget-box">
                            <div class="span6">
                                <table class="table" id="table_usersNoGroup">
                                    <thead>

                                    <tr>
                                        <th>
                                            Nombre
                                        </th>
                                        <th>
                                            Email
                                        </th>
                                        <th>
                                        </th>
                                    </tr>
                                    </thead>
                                </table>
                                <style type="text/css">
                                    .tbl-searchbox {
                                        padding: 0px 20px 14px 0px;
                                    }
                                </style>
                            </div>
                            <div class="span6">
                                <table class="table" id="table_usersGroup">
                                    <thead>

                                    <tr>
                                        <th>
                                            Nombre
                                        </th>
                                        <th>
                                            Email
                                        </th>
                                        <th>
                                        </th>
                                    </tr>
                                    </thead>
                                </table>
                                <style type="text/css">
                                    .tbl-searchbox {
                                        padding: 0px 20px 14px 0px;
                                    }
                                </style>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div id="tabs-2">
                <div class="widget-block">
                    <div class="widget-head">
                        <h5>PERMISOS</h5>

                        <div class="widget-control pull-right" id="permisosAddSection">
                            <div class="pull-right" style="padding-left: 20px">
                                <a class="info_t btn" onclick="permisos.add()"><i class="color-icons add_co"></i>Agregar</a>
                            </div>
                            <div class="pull-right">
                                <select style="width: 120px; height: 40px" name="roles" id="roles">
                                    {% for rol in roles %}
                                        <option value="{{ rol.getValor }}">{{ rol.getNombre }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="widget-content">
                        <div class="widget-box">
                            <form class="form-horizontal" method="post">
                                {% csrf_token %}
                                <fieldset>
                                    <div class="span6">
                                        <div class="tree" style="overflow-y: scroll; height: 300px">
                                            {% load mptt_tags %}
                                            <ul>
                                                {% recursetree nodes %}
                                                    <li>
                                                        <span><input type="radio" name="permisos" id="{{ node.id }}"
                                                                     value="{{ node.id }}"/><i
                                                                class="icon-calendar"></i> {{ node.nombre }}</span>
                                                        {% if not node.is_leaf_node %}
                                                            <ul class="children">
                                                                {{ children }}
                                                            </ul>
                                                        {% endif %}
                                                    </li>
                                                {% endrecursetree %}
                                            </ul>
                                        </div>
                                    </div>
                                    <style>
                                        .tbl-searchbox {
                                            padding: 0px 20px 14px 0px;
                                        }
                                    </style>
                                    <div class="span6">
                                        <table class="table" id="table_permissions">
                                            <thead>

                                            <tr>
                                                <th>
                                                    Nombre
                                                </th>
                                                <th>
                                                    Rol
                                                </th>
                                                <th>
                                                </th>
                                            </tr>
                                            </thead>
                                        </table>
                                        <style type="text/css">
                                            .tbl-searchbox {
                                                padding: 0px 20px 14px 0px;
                                            }
                                        </style>
                                    </div>
                                </fieldset>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="modal_confirmacion" title="Eliminar Permiso">
    <div class="modal-body">
        ¿Está seguro que desea eliminar el permiso: <b><span id="nombre_permiso"></span></b>?
    </div>
</div>

<div id="modal_edicion" title="Editar Permiso" style="overflow-y:hidden">
    <form id="form_update_permission" class="form-horizontal">
        <div class="modal-body">
            <fieldset>
                <div class="control-group">
                    <label class="control-label" for="id_nombre">Nombre : </label>

                    <div class="controls">
                        <span id="nombrePermisoEditar" style="font-weight: bold"></span>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="id_nombre">Rol : </label>

                    <div class="controls">
                        <select style="width: 120px" name="rolesEditar" id="rolesEditar">
                            {% for rol in roles %}
                                <option value="{{ rol.getValor }}">{{ rol.getNombre }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
            </fieldset>
        </div>
        <div class="modal-footer">
            <button class="btn btn-info" id="bUpdatePermission">
                Actualizar
            </button>
            <button class="btn btn-warning" id="cancelUpdatePermission">
                Cancelar
            </button>
        </div>
    </form>
</div>

SGSISoft/gestion_roles/templates/grupo_form.html
<!--
Autor: Andres Betin, Jhonny Madera y Raul Martelo
Copyright: Copyright 2016, Universidad de Cartagena
Credits: Andres Betin, Jhonny Madera, Raul Martelo,
         Grupo de investigacion GIMATICA
         Universidad de Cartagena
License: GPL
Version: 1.0.0
Status: Production
-->

<div class="container-fluid">
    <div class="row-fluid">
        <div class="span12">
            <div class="nonboxy-widget">
                <div class="widget-content">
                    <div class="widget-box">
                        <div class="alert alert-success fade in" style="display: none">
                            <button data-dismiss="alert" class="close" type="button">×</button>
                            <strong>Actividad creada!</strong> Su actividad se ha creada de manera éxitosa se le
                            notificara a los usuarios encargados.
                        </div>

                        <form id="formGroup" class="form-horizontal well" method="POST" action="">
                            {% csrf_token %}
                            <fieldset>
                                <div class="control-group">
                                    <label class="control-label" for="id_nombre">Nombre</label>

                                    <div class="controls">
                                        {{ formulario.nombre }}
                                    </div>
                                </div>
                                {% comment %}                                    
                                    <div class="control-group">
                                        <label class="control-label" for="id_personas">Miembros</label>

                                        <div class="controls">
                                            {{ formulario.personas }}
                                        </div>
                                    </div>
                                {% endcomment %}
                                <div class="form-actions">
                                    {% if editId %}
                                        <button id="saveFormGroup" href="{% url eGrupo_ajax editId %}" type="submit"
                                                class="btn btn-info">Guardar
                                        </button>
                                    {% else %}
                                        <button id="saveFormGroup" href="{% url nGrupo_ajax %}" type="submit"
                                                class="btn btn-info">Guardar
                                        </button>
                                    {% endif %}
                                    <button id="cancelFormGroup" class="btn btn-warning">Cancelar</button>
                                </div>
                            </fieldset>
                        </form>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

SGSISoft/gestion_roles/templates/restablecer_contrasena.html
<!--
Autor: Andres Betin, Jhonny Madera y Raul Martelo
Copyright: Copyright 2016, Universidad de Cartagena
Credits: Andres Betin, Jhonny Madera, Raul Martelo,
         Grupo de investigacion GIMATICA
         Universidad de Cartagena
License: GPL
Version: 1.0.0
Status: Production
-->

{% extends 'dashboard.html' %}

{% block zonaTrabajo%}
<div class="container-fluid">
        <div class="row-fluid">
            <div class="span12">
                <div class="nonboxy-widget">
                    <div class="widget-head">
                        <h5>Cambiar Contrase&ntilde;a</h5>
                    </div>
                    <div class="widget-content well">

                        <div class="widget-box">
                            <form id="formUser" class="form-horizontal" method="post">
                                <fieldset>
                                    <div class="cuerpo-formulario">
                                        <div class="marco-formulario">
                                            <form id='formulario' method="post" action="">
                                                {% csrf_token %}
                                                {{formulario}}
                                                <div class="form-actions">
                                                    <button type="submit" class="btn btn-info">Reestablecer</button>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </fieldset>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
{% endblock %}