SGSISoft/SGSISoft/urls.py
__author__ = "Andres Betin, Jhonny Madera y Raul Martelo"
__copyright__ = "Copyright 2016, Universidad de Cartagena"
__credits__ = ["Andres Betin", "Jhonny Madera", "Raul Martelo",
                    "Grupo de Investigacion GIMATICA",
                    "Universidad de Cartagena"]
__license__ = "GPL"
__version__ = "1.0.0"
__status__ = "Production"

from django.conf.urls import patterns, include, url
from django.contrib import admin

#from model_report import report
import notifications
from django.conf import settings

admin.autodiscover()
#report.autodiscover()

urlpatterns = patterns('',

                       url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
                       url(r'^admin/', include(admin.site.urls)),
                       url('^inbox/notifications/', include(notifications.urls)),
                       url(r'', include('user_sessions.urls', 'user_sessions')),
                       url(r'^pass/', include('password_reset.urls')), #TODO Corregir paginas
                       url(r'^', include('home.urls')),
                       url(r'^autoevaluacion/', include('autoevaluacion.urls')),
                       url(r'^activos/', include('gestion_activos.urls')),
                       url(r'^documental/', include('gestion_documental.urls')),
                       url(r'^riesgos/', include('gestion_riesgos.urls')),
                       url(r'^roles/', include('gestion_roles.urls')),
                       url(r'^reports/', include('reports.urls')),
                       url(r'^upload/', include('fileupload.urls')),
                       #url(r'^reportes/', include('model_report.urls')),


)
urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

SGSISoft/gestion_documental/urls.py
# -*- encoding: utf-8 -*-
__author__ = "Andres Betin, Jhonny Madera y Raul Martelo"
__copyright__ = "Copyright 2016, Universidad de Cartagena"
__credits__ = ["Andres Betin", "Jhonny Madera", "Raul Martelo",
                    "Grupo de Investigacion GIMATICA",
                    "Universidad de Cartagena"]
__license__ = "GPL"
__version__ = "1.0.0"
__status__ = "Production"

from gestion_documental.views import *
from django.conf.urls import patterns, url

urlpatterns = patterns('',
    #url(r'^$', index, name='documental.index'),
    #views Render
    url(r'^document/new/([\d]+)$', documentNewRender, name='nDocumento'),#Mostrar: pagina para CREAR documento
    url(r'^document/edit/([\d]+)$', documentEditRender, name='eDocumento'),#Mostrar: pagina para EDITAR
    url(r'^document$', documentAllRender, name='lDocumento'),#Mostrar: pagina para listar documentos del usuario 'mis documentos'
    url(r'^document/admin$', documentAdminRender, name='allDocumento'),#Mostrar: pagina para mostrar TODOS los documentos
    url(r'^document/([\d]+)$', documentRender, name='vDocumento'),#Detalle: informacion de un documento
    url(r'^document/upload$', documentUpload, name='uploadDocumento'),#Detalle: informacion de un documento
    url(r'^document/versioning$', documentVersioning, name='versioningDocumento'),#Detalle: informacion de un documento

    url(r'^document/all$', documentRead, name='documentRead'),#Listar: documentos
    url(r'^document/delete$', documentDelete, name='documentDelete'),#Eliminar documento
    url(r'^document/change/status$', documentChangeStatus, name='documentChangeStatus'),#Actualizar: modificar estado de documento

    url(r'^observation/create$', observationCreate, name='observationCreate'),#Crear: observacion
    url(r'^observation/document/([\d]+)$', observationRender, name='oDocumento'),#Listar: observaciones de documento determinado

    url(r'^activity$', activityAllRender, name='lActividad'),#Mostrar: pagina para listar actividades del usuario conectado
    url(r'^activity/all$', activityRead, name='activityRead'),#Listar: actividades
    url(r'^activity/new$', activityNewRender, name='nActividad'),#Mostrar: formulario para crear actividad
    url(r'^activity/new_ajax$', activityNewPost, name='nActividad_ajax'),#ajax: Ajax para CREAR actividad.
    url(r'^activity/edit/([\d]+)$', activityEditRender, name='eActividad'),#Mostrar: formulario para EDITAR actividad
    url(r'^activity/edit_ajax/([\d]+)$', activityEditPost, name='eActividad_ajax'),#ajax: ajax para EDITAR actividad
    url(r'^activity/delete$', activityDelete, name='activityDelete'),#Eliminar: actividades
    url(r'^activity/user/([\d]+)$', activityUserRender, name='uActividad'),#Mostrar: pagina LISTAR actividades de usuario TODO: quitar.
    url(r'^activity/admin$', activityAdminRender, name='allActividad'),#Mostrar : pagina para LISTAR TODAS las actividades
    url(r'^activity/([\d]+)$', activityRender, name='vActividad'),#Detalle: informacion de actividad
    url(r'^activity/documents/([\d]+)$', activityDocuments, name='vActividadDocuments'),#Detalle: documentos asociados a una actividad.

    url(r'^calendar$', calendarRender, name='calendario'),#Mostrar pagina de inicio con calendario

)

SGSISoft/home/urls.py
# -*- encoding: utf-8 -*-
__author__ = "Andres Betin, Jhonny Madera y Raul Martelo"
__copyright__ = "Copyright 2016, Universidad de Cartagena"
__credits__ = ["Andres Betin", "Jhonny Madera", "Raul Martelo",
                    "Grupo de Investigacion GIMATICA",
                    "Universidad de Cartagena"]
__license__ = "GPL"
__version__ = "1.0.0"
__status__ = "Production"

from django.conf.urls import patterns, url
from home.views import *

urlpatterns = patterns('',
        url(r'^$', home, name='inicio'),
        url(r'^login$', login, name='login'),
        url(r'^logout$', logout_view, name='logout'),
        #url(r'^notification$', notificationRender, name='notificaciones'), TODO: eliminar o reimplementar
        #url(r'^notification/([\d]+)$', notificationDetailRender, name='eNotificacion'), TODO: eliminar o reimplementar
        url(r'^notifications$', notificationsRead, name='notifications_ajax_read'),
)

SGSISoft/gestion_documental/models.py
# -*- encoding: utf-8 -*-
__author__ = "Andres Betin, Jhonny Madera y Raul Martelo"
__copyright__ = "Copyright 2016, Universidad de Cartagena"
__credits__ = ["Andres Betin", "Jhonny Madera", "Raul Martelo",
                    "Grupo de Investigacion GIMATICA",
                    "Universidad de Cartagena"]
__license__ = "GPL"
__version__ = "1.0.0"
__status__ = "Production"

import uuid
import os
from django.db import models

# Create your models here.
from gestion_roles.models import Persona
from util.Util import EnumElemento

# region Enumeraciones
class TipoActividad:
    ISO=EnumElemento("ISO", 1)
    INFORME=EnumElemento("Informe", 2)

    @staticmethod
    def listaEnumerada():
        return [(value.getValor(), value.getNombre()) for key, value in TipoActividad.__dict__.iteritems() if isinstance(value, EnumElemento)]

    @staticmethod
    def listaElementos():
        return [value for key, value in TipoActividad.__dict__.iteritems() if isinstance(value, EnumElemento)]

    @staticmethod
    def get(id):
        valord= [value for key, value in TipoActividad.__dict__.iteritems() if isinstance(value, EnumElemento) and value.getValor()==id][0]
        return valord

class EstadoActividad:
    CREADA=EnumElemento("Creada", 3,estilo = 'label-default')
    ACTIVA=EnumElemento("Activa", 1, estilo = 'label-success')
    INACTIVA=EnumElemento("Inactiva", 2,estilo = 'label-default')
    RESUELTA=EnumElemento("Resuelta", 3,estilo = 'label-default')
    CERRADA=EnumElemento("Cerrada", 3,estilo = 'label-warning')

    @staticmethod
    def listaEnumerada():
        return [(value.getValor(), value.getNombre()) for key, value in EstadoActividad.__dict__.iteritems() if isinstance(value, EnumElemento)]

    @staticmethod
    def listaElementos():
        return [value for key, value in EstadoActividad.__dict__.iteritems() if isinstance(value, EnumElemento)]

    @staticmethod
    def get(id):
        valord= [value for key, value in EstadoActividad.__dict__.iteritems() if isinstance(value, EnumElemento) and value.getValor()==id][0]
        return valord

class TipoDocumento:
    ISO=EnumElemento("ISO", 1)
    INFORME=EnumElemento("Informe", 2)

    @staticmethod
    def listaEnumerada():
        return [(value.getValor(), value.getNombre()) for key, value in TipoDocumento.__dict__.iteritems() if isinstance(value, EnumElemento)]

    @staticmethod
    def listaElementos():
        return [value for key, value in TipoDocumento.__dict__.iteritems() if isinstance(value, EnumElemento)]

    @staticmethod
    def get(id):
        valord= [value for key, value in TipoDocumento.__dict__.iteritems() if isinstance(value, EnumElemento) and value.getValor()==id][0]
        return valord

class EstadoDocumento:
    BORRADOR=EnumElemento("Borrador", 1, estilo='label-default', icon='')
    VERIFICAR=EnumElemento("Verificar", 2 , estilo='label-info',icon = 'icon-edit')
    REVISION=EnumElemento("Revisión", 3, estilo='label-warning', icon = 'icon-check')
    APROBADO=EnumElemento("Aprobado", 4, estilo = 'label-inverse',icon = 'icon-ok')
    PUBLICADO=EnumElemento("Publicado", 5, estilo = 'label-success', icon = 'icon-globe')

    @staticmethod
    def listaEnumerada():
        return [(value.getValor(), value.getNombre()) for key, value in EstadoDocumento.__dict__.iteritems() if isinstance(value, EnumElemento)]

    @staticmethod
    def listaElementos():
        return [value for key, value in EstadoDocumento.__dict__.iteritems() if isinstance(value, EnumElemento)]

    @staticmethod
    def get(id):
        valord = [value for key, value in EstadoDocumento.__dict__.iteritems() if isinstance(value, EnumElemento) and value.getValor()==id][0]
        return valord
# endregion

# region NoBorrables
class Actividad(models.Model):
    titulo = models.CharField(max_length=50)
    inicio = models.DateField()
    fin = models.DateField()
    descripcion = models.TextField()
    estadoActividad = models.IntegerField(choices=EstadoActividad.listaEnumerada())
    tipoActividad = models.IntegerField(choices=TipoActividad.listaEnumerada())
    responsables = models.ManyToManyField(Persona)

# region Auditoria
    isDisable= models.BooleanField(default=False)
    createDate= models.DateTimeField(auto_now_add=True)
    createUser= models.TextField(null=True, blank=True)
    updateDate= models.DateTimeField(auto_now=True)
    updateUser= models.TextField(null=True, blank=True)

    def setDisable(self, disable):
        self.isDisable= disable

    def setUpdateUser(self, user):
        self.updateUser= user

    def setCreateUser(self, user):
        self.createUser= user
        self.updateUser= user
# endregion
    def __unicode__(self):
        return self.titulo


def get_file_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    return os.path.join('files', filename)

class VersionDocumento(models.Model):
    version = models.TextField()
    archivo = models.FileField(upload_to=get_file_path)

# region Auditoria
    isDisable= models.BooleanField(default=False)
    createDate= models.DateTimeField(auto_now_add=True)
    createUser= models.TextField(null=True, blank=True)
    updateDate= models.DateTimeField(auto_now=True)
    updateUser= models.TextField(null=True, blank=True)

    def setDisable(self, disable):
        self.isDisable= disable

    def setUpdateUser(self, user):
        self.updateUser= user

    def setCreateUser(self, user):
        self.createUser= user
        self.updateUser= user
# endregion
    def __unicode__(self):
        return self.version

class Documento(models.Model):
    titulo = models.CharField(max_length=50)
    descripcion = models.TextField(blank=True)
    estadoDocumento = models.IntegerField(choices=EstadoDocumento.listaEnumerada())
    tipoDocumento = models.IntegerField(choices=TipoDocumento.listaEnumerada())
    actividad = models.ForeignKey(Actividad)
    versiones = models.ManyToManyField(VersionDocumento, related_name='documento')
    versionActual = models.ForeignKey(VersionDocumento, related_name='documentoActual')

# region Auditoria
    isDisable= models.BooleanField(default=False)
    createDate= models.DateTimeField(auto_now_add=True)
    createUser= models.TextField(null=True, blank=True)
    updateDate= models.DateTimeField(auto_now=True)
    updateUser= models.TextField(null=True, blank=True)

    def setDisable(self, disable):
        self.isDisable= disable

    def setUpdateUser(self, user):
        self.updateUser= user

    def setCreateUser(self, user):
        self.createUser= user
        self.updateUser= user
# endregion
    def __unicode__(self):
        return self.titulo

class Observacion(models.Model):
    autor = models.ForeignKey(Persona)
    descripcion = models.TextField()
    documento = models.ForeignKey(Documento)

# region Auditoria
    isDisable= models.BooleanField(default=False)
    createDate= models.DateTimeField(auto_now_add=True)
    createUser= models.TextField(null=True, blank=True)
    updateDate= models.DateTimeField(auto_now=True)
    updateUser= models.TextField(null=True, blank=True)

    def setDisable(self, disable):
        self.isDisable= disable

    def setUpdateUser(self, user):
        self.updateUser= user

    def setCreateUser(self, user):
        self.createUser= user
        self.updateUser= user
# endregion
    def __unicode__(self):
        return self.descripcion
# endregion

SGSISoft/gestion_documental/forms/ActividadForm.py
# -*- encoding: utf-8 -*-
__author__ = "Andres Betin, Jhonny Madera y Raul Martelo"
__copyright__ = "Copyright 2016, Universidad de Cartagena"
__credits__ = ["Andres Betin", "Jhonny Madera", "Raul Martelo",
                    "Grupo de Investigacion GIMATICA",
                    "Universidad de Cartagena"]
__license__ = "GPL"
__version__ = "1.0.0"
__status__ = "Production"

from util.Comunicaciones.NotificacionesUtil import NotificacionesUtil

from gestion_documental.servicios import ActividadServicios
from util.Comunicaciones.CorreoUtil import CorreoUtil
from django import forms
from django.forms.models import ModelForm
from gestion_documental.models import *
from datetime import date

class ActividadForm(ModelForm):
    def __init__(self, *args, **kwargs):
        self.edit = kwargs.pop('edit', None)
        self.id = kwargs.pop('id', None)
        self.user = kwargs.pop('user', None)
        super(ActividadForm, self).__init__(*args, **kwargs)

        #Definicion de elementos necesarios
        self.actividadServicio= ActividadServicios()

    class Meta:
        model = Actividad
        exclude = ['estadoActividad', 'fecha_creacion']
        atributos = {'data-placeholder': "Seleccionar", 'class': "chzn-select", 'tabindex': "2"}
        actividad = {'title': 'Titulo para identificar la actividad', 'class': 'span8 text-tip'}
        descripcion = {'rows': '8', 'class': 'span8'}
        responsables = {'class': 'chzn-select', 'multiple': '', 'tabindex': '15', 'style': 'width:210px'}

        widgets = {
            'tipoActividad': forms.Select(attrs=atributos),
            'titulo': forms.TextInput(attrs=actividad),
            'descripcion': forms.Textarea(attrs=descripcion),
            'responsables': forms.SelectMultiple(attrs=responsables),
        }

    def clean(self):
        form = super(ActividadForm, self).clean()
        inicio = form.get("inicio")
        fin = form.get("fin")

        if (not (fin >= date.today() and inicio >= date.today())):
            raise forms.ValidationError("Las fechas deben ser mayores o iguales a la actual")
        if (inicio > fin):
            raise forms.ValidationError("Las fecha inicial debe ser menor que la fecha final")

        return form

    def save(self, commit=True):
        if not self.edit:
            #TODO: validar que la actividad tenga por lo menos un responsable.
            actividad = super(ActividadForm, self).save(commit=False)
            actividad.estadoActividad = EstadoActividad.ACTIVA.getValor()
            self.actividadServicio.insert(actividad)
            self.save_m2m()

            notificacionesUtil=NotificacionesUtil()
            notificacionesUtil.notificarNuevaActividad(self.user,actividad);
            correoUtil=CorreoUtil()
            correoUtil.correoCreacionActividad(actividad, actividad.responsables.all())
        else:
            actividad = super(ActividadForm, self).save(commit=False)

            self.save_m2m()
            self.actividadServicio.update(actividad)
            #TODO: notificar a los interesados del cambio de actividad.

SGSISoft/gestion_documental/templates/actividad_form.html
<!--
Autor: Andres Betin, Jhonny Madera y Raul Martelo
Copyright: Copyright 2016, Universidad de Cartagena
Credits: Andres Betin, Jhonny Madera, Raul Martelo,
         Grupo de investigacion GIMATICA
         Universidad de Cartagena
License: GPL
Version: 1.0.0
Status: Production
-->

    <div class="container-fluid">
        <div class="row-fluid">
            <div class="span12">
                <div class="nonboxy-widget">
                    <div class="widget-content well">
                        <div class="widget-box">
                            <form id="formActividad" class="form-horizontal" method="POST" action="">
                                <fieldset>
                                    <div>
                                        <div id="id___all__"></div>
                                    </div>
                                    <div class="control-group">
                                        <label class="control-label" for="id_titulo">Titulo</label>
                                        <div class="controls">
                                            {{ formulario.titulo }}
                                        </div>
                                    </div>
                                    <div class="control-group">
                                        <label class="control-label" for="typehead">Encargado</label>
                                        <div class="controls">
                                            {{ formulario.responsables }}
                                        </div>
                                    </div>
                                    <div class="control-group">
                                        <label class="control-label" >Inicio</label>

                                        <div class="controls">
                                            {{ formulario.inicio }}
                                        </div>
                                    </div>
                                    <div class="control-group">
                                        <label class="control-label" >Fin</label>

                                        <div class="controls">
                                            {{ formulario.fin }}
                                        </div>
                                    </div>

                                    <div class="control-group">
                                        <label class="control-label"> Tipo</label>
                                        <div class="controls">
                                            {{ formulario.tipoActividad }}
                                        </div>
                                    </div>

                                    <div class="control-group">
                                        <label class="control-label">Descripción</label>
                                        <div class="controls">
                                            {{ formulario.descripcion }}
                                        </div>
                                    </div>
                                    <div class="form-actions">
                                        {% if editId%}
                                            <button id="saveForm" href="{% url eActividad_ajax editId %}" type="submit" class="btn btn-info">Guardar</button>
                                        {% else%}
                                            <button id="saveForm" href="{% url nActividad_ajax %}" type="submit" class="btn btn-info">Guardar</button>
                                        {% endif %}
                                        <button id="cancelForm" class="btn btn-warning">Cancelar</button>
                                    </div>
                                </fieldset>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

        </div>


    </div>

    </div>

SGSISoft/gestion_documental/templates/actividad_listar.html
<!--
Autor: Andres Betin, Jhonny Madera y Raul Martelo
Copyright: Copyright 2016, Universidad de Cartagena
Credits: Andres Betin, Jhonny Madera, Raul Martelo,
         Grupo de investigacion GIMATICA
         Universidad de Cartagena
License: GPL
Version: 1.0.0
Status: Production
-->

{% extends "dashboard.html" %}

{% block zonaTrabajo %}
    <script>
        $(document).ready(function () {
            actividades.tipo = "{{ tipo }}"
            actividades.inicializar()
        });
    </script>
    <div class="container-fluid">
        <div class="row-fluid">
            <div class="span12">
                <div class="widget-block">
                    <div class="widget-head">
                        <h5>Actividades</h5>
                        <div id="datos"></div>
                        <div class="widget-control pull-right">
                            <a class="btn" href="{% url nActividad %}" id="newActividad"><i class="color-icons add_co"></i>Nueva</a>
                        </div>
                    </div>
                    <div class="widget-content">
                        <div class="widget-box">
                            <table id="table_activity" class="table">
                                <thead>
                                <tr>
                                    <th>
                                        Titulo
                                    </th>
                                    <th>
                                        Tipo
                                    </th>
                                    <th>
                                        Inicio
                                    </th>
                                    <th>
                                        Finalización
                                    </th>
                                    <th>
                                        Estado
                                    </th>
                                    <th>
                                        Descripción
                                    </th>
                                    <th></th>
                                </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="window_actividad" title="Actividad">
        <div id="content"></div>
    </div>

<div id="dialog-confirm" title="Eliminar Actividad">
  <p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>¿Está seguro que desea eliminar la actividad: <b><span id="nombre_actividad"></span></b>?</p>
</div>

{% endblock %}

SGSISoft/gestion_documental/templates/documento_form.html
<!--
Autor: Andres Betin, Jhonny Madera y Raul Martelo
Copyright: Copyright 2016, Universidad de Cartagena
Credits: Andres Betin, Jhonny Madera, Raul Martelo,
         Grupo de investigacion GIMATICA
         Universidad de Cartagena
License: GPL
Version: 1.0.0
Status: Production
-->

    <div class="container-fluid">
        <div class="row-fluid">
            <div class="span12">
                <div class="nonboxy-widget">
                    <div class="widget-content">
                        <div class="widget-box">
                            <div id="form-wrapper" >
                            <form id="fileupload" class="form-horizontal well" method="POST" enctype="multipart/form-data">
                                {% csrf_token %}
                                <fieldset>
                                    <div class="control-group">
                                        <label class="control-label"
                                               for="id_titulo">Titulo {{ formulario.actividad }}</label>

                                        <div class="controls">
                                            {{ formulario.titulo }}
                                            {# {{ formulario.titulo.errors }}#}
                                        </div>
                                        <br/>
                                        <label class="control-label"
                                               for="id_titulo">Descripci&oacute;n</label>
                                        <div class="controls">
                                            {{ formulario.descripcion }}
                                            {# {{ formulario.descripcion.errors }}#}
                                        </div>
                                        <br/>
                                        <label class="control-label"
                                               for="id_titulo">Tipo Documento</label>
                                        <div class="controls">
                                            {{ formulario.tipoDocumento }}
                                            {# {{ formulario.tipoDocumento.errors }}#}
                                        </div>
                                    </div>
                                    <div class="control-group">
                                        <label class="control-label">Archivo</label>

                                        <div class="controls">
                                            <!-- The fileinput-button span is used to style the file input field as button -->
                                            <span class="btn btn-success fileinput-button">
                                                <i class="glyphicon glyphicon-plus"></i>
                                                <span>Archivo...</span>
                                                <input id="uploaded-files" type="file" name="files">
                                            </span>
                                        </div>
                                    </div>

                                                                        <!-- The global progress state -->
                                    <div class="col-lg-5 fileupload-progress fade">
                                        <!-- The global progress bar -->
                                        <div class="progress progress-striped active" role="progressbar"
                                             aria-valuemin="0" aria-valuemax="100">
                                            <div class="progress-bar progress-bar-success" style="width:0%;"></div>
                                        </div>
                                        <!-- The extended global progress state -->
                                        <div class="progress-extended">&nbsp;</div>
                                    </div>
                                     <!-- The table listing the files available for upload/download -->
                                <table role="presentation" class="table table-striped">
                                    <tbody class="files"></tbody>
                                </table>

                                    <div class="form-actions">

                                        {% comment %}<button type="submit" class="btn btn-info">Guardar</button>
                                        <button class="btn btn-warning">Cancelar</button>{% endcomment %}
                                    </div>
                                </fieldset>
                                <!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
                                <div class="row fileupload-buttonbar">
                                    <div class="col-lg-7">
                                        <button type="button" id="buttonFileUpload" class="btn btn-primary start">
                                            <i class="glyphicon glyphicon-upload"></i>
                                            <span>Crear Documento</span>
                                        </button>
                                        <button type="reset" class="btn btn-warning cancel">
                                            <i class="glyphicon glyphicon-ban-circle"></i>
                                            <span>Cancelar</span>
                                        </button>
                                        <!-- The global file processing state -->
                                        <span class="fileupload-process"></span>
                                    </div>
                                </div>

                            </form>
                        </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

<!-- Generic page styles -->
<link rel="stylesheet" href="{{ STATIC_URL }}css/jquery-file-uploader/style.css">

<!-- CSS to style the file input field as button and adjust the Bootstrap progress bars -->
<link rel="stylesheet" href="{{ STATIC_URL }}css/jquery-file-uploader/jquery.fileupload.css">
<link rel="stylesheet" href="{{ STATIC_URL }}css/jquery-file-uploader/jquery.fileupload-ui.css">

<![endif]-->